name: Publish Packages to NPM

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install mise
        uses: jdx/mise-action@v2
      - name: Install dependencies
        run: npm ci
      - name: Build packages
        run: npm run build -w @xennis/react-notion-cms-fetch -w @xennis/react-notion-cms-render
      - name: Set publishing config
        run: npm config set '//registry.npmjs.org/:_authToken' "${NODE_AUTH_TOKEN}"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Publish packages
        run: npm publish --workspaces --access=public
